import React from 'react'

const About = () => {
  return (
    <div>
     <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil odit magni perspiciatis? Incidunt voluptatem reprehenderit cumque, aut impedit temporibus. Repellendus, mollitia? Asperiores aspernatur perspiciatis nihil deleniti tenetur unde, in ex. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat, temporibus! Corrupti consectetur, labore cupiditate earum voluptate quis repellat voluptatibus nulla? Blanditiis vitae voluptatibus, laborum illum harum doloribus vel vero, ex, tempora consequatur sit! Illum vel corporis minima unde repudiandae recusandae doloremque reiciendis impedit eveniet fugiat blanditiis dolor quam laboriosam nam pariatur, enim sit odio assumenda fugit deleniti eos. Necessitatibus dicta itaque saepe voluptas aperiam, unde est quas quasi expedita, asperiores maxime dolorem dignissimos. Quas harum voluptatibus repellendus distinctio praesentium enim reiciendis iusto nemo est veritatis. Dolor nesciunt nobis earum ullam, necessitatibus repellat aperiam. Maiores labore alias repellat inventore error itaque incidunt sequi ex reprehenderit in dicta quidem voluptatum, est atque at totam culpa consectetur, libero id! Soluta ab voluptatum tempore, quaerat minus autem itaque. Dolore, facilis? Itaque molestiae eaque, optio, repellendus repellat, saepe qui voluptas hic quam totam maiores culpa explicabo mollitia. Fugit iure vel odio est doloribus laborum ea nam quis magni facere commodi, ducimus reiciendis distinctio suscipit nobis illum ut optio eum, modi velit accusamus vitae quam! Similique hic rerum veritatis iste. Voluptas deleniti suscipit at corporis ad. Magnam soluta sapiente repellendus nemo voluptates, repellat dolor est numquam, animi rem minima. Deleniti, fuga sed. Pariatur tempora veniam natus.</p> 
     <p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident at ducimus, soluta praesentium cupiditate dolores mollitia, quia nemo neque, qui rem? Architecto quibusdam, mollitia, obcaecati quos, dolore sit saepe possimus fugiat sunt numquam iure nisi corrupti eaque ea. Necessitatibus, sunt dicta delectus id commodi molestiae voluptatibus quidem quo similique. Aperiam, veniam explicabo. Magnam unde inventore maiores recusandae possimus provident iste labore voluptatum! Totam labore quae nobis dolore perspiciatis, porro illum.</p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem maxime fugit quam eligendi minus perspiciatis, illo ab unde, nesciunt non deleniti exercitationem quia laudantium. Consequatur vitae aliquam possimus distinctio ratione non, eius consequuntur? Ipsum, vero nam? Ratione inventore sit consequatur, placeat ut sequi vel ea molestias eum reprehenderit voluptas nobis ipsa recusandae? Officia aut facere repellat reiciendis dolore in exercitationem pariatur quaerat praesentium amet autem animi ipsa ducimus maiores ex vitae accusamus, ipsum aperiam omnis id quidem illo deleniti. Et fugiat alias dolore excepturi cum, quam quas iusto dolor, soluta non voluptates fugit! Soluta reiciendis iusto, ad, laudantium labore officia, rem repellat ex quod natus dolorum consectetur earum rerum porro nobis. Repellat rem, maxime labore quo saepe animi dolore eligendi assumenda libero possimus voluptatum iusto explicabo, architecto commodi fugit corporis blanditiis illo suscipit quisquam illum. Neque totam accusantium quidem ducimus perspiciatis, aliquam sit officiis molestias adipisci earum consequuntur, vero minus eligendi quibusdam saepe beatae voluptatum porro architecto, optio repudiandae incidunt temporibus maiores? Aut, culpa. Laboriosam quod aliquam doloribus iste officiis reiciendis sunt dignissimos iusto nostrum. Animi obcaecati ex sit eaque quam nobis odio aliquid dicta alias ducimus cupiditate nisi incidunt expedita, illum similique. Itaque molestiae tempora adipisci magni quidem provident.
     </p>
     About Page Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis dolorum libero architecto quod nesciunt corporis incidunt autem odio obcaecati repellat provident impedit, dolores voluptates, ratione quasi? Itaque veniam tempore natus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore vel ducimus magnam totam minima qui odit repudiandae, rem aut sapiente atque et magni laudantium quia, illum fuga neque odio rerum omnis animi tempora soluta quibusdam? Ducimus, blanditiis dignissimos unde nihil, nulla provident necessitatibus vel praesentium saepe possimus sapiente rerum accusantium amet id qui ipsa, impedit nobis perferendis? Aspernatur ratione libero omnis hic dignissimos at quam animi laborum atque fugit placeat velit eos, enim perferendis. Nesciunt animi asperiores dolorem reiciendis est voluptatem harum. Fuga distinctio, eveniet explicabo vero enim, consequuntur aperiam ex vitae ea accusantium est tempora impedit asperiores error sint libero. Dolores vel rem id voluptatibus distinctio pariatur? Molestias, et, quas a eius vel provident consequatur nobis magnam error laboriosam esse nesciunt ipsam alias sint facilis expedita eaque atque deleniti maiores dolores, veritatis sapiente? Autem natus sequi nihil iste? Dicta odio magni in sequi unde atque libero quos blanditiis aperiam! Culpa, exercitationem sunt? Possimus eius voluptates consequatur qui quisquam modi commodi iste obcaecati est blanditiis hic, distinctio quos, eum ipsa esse ab aliquam. Obcaecati vel inventore error, eum dignissimos, debitis tempore quasi itaque ratione neque voluptates maiores alias voluptas saepe nam aliquam explicabo accusantium officia non impedit id veniam facere? Consequuntur aperiam tempore modi, enim cupiditate perferendis dicta aliquid ipsum ipsam doloribus beatae ducimus sed reiciendis nostrum est assumenda deleniti nulla iste ipsa repellendus explicabo! Illo natus dolor, recusandae beatae corporis veniam, delectus consectetur incidunt dolore ab blanditiis ipsum? Iste vel nobis neque at! Similique quo eveniet, corporis culpa ducimus deserunt animi sint dolores qui pariatur quia autem magnam doloribus id rerum cupiditate. Repudiandae vitae fugiat sint vel tempora eos deleniti illum facilis dolor dolores delectus iste amet officia rerum, quos illo? Reiciendis ab nobis quis voluptates at, voluptatem, qui officia quia consectetur aperiam culpa dolores laborum voluptatibus, accusamus nihil.
        
    </div>
  )
}

export default About
